# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('push_date', models.CharField(blank=True, max_length=45, null=True)),
                ('viewtime', models.CharField(blank=True, max_length=45, null=True)),
                ('blog_content', models.CharField(blank=True, max_length=20000, null=True)),
                ('comment_num', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'blog_detail',
                'managed': False,
            },
        ),
    ]
