# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(max_length=249, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=45, null=True)),
                ('text', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
    ]
