# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('create_date', models.CharField(blank=True, max_length=45, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('url_object_id', models.CharField(blank=True, max_length=45, null=True)),
                ('front_image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('front_image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('praise_nums', models.CharField(blank=True, max_length=45, null=True)),
                ('fav_nums', models.CharField(blank=True, max_length=45, null=True)),
                ('content', models.CharField(blank=True, max_length=20000, null=True)),
                ('tags', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
    ]
