# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_url', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('pt_time', models.CharField(blank=True, max_length=100, null=True)),
                ('good_num', models.IntegerField(blank=True, null=True)),
                ('comm_num', models.IntegerField(blank=True, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('repost_num', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=255, null=True)),
                ('poster', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('tweets_num', models.IntegerField(blank=True, null=True)),
                ('follow_num', models.IntegerField(blank=True, null=True)),
                ('fan_num', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('authentication', models.CharField(blank=True, max_length=255, null=True)),
                ('abstract', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
